// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/psn-polish/CardsShowcase.tsx": () => import("../components/mockups/psn-polish/CardsShowcase.tsx"),
  "./components/mockups/psn-polish/CasesScreen.tsx": () => import("../components/mockups/psn-polish/CasesScreen.tsx"),
  "./components/mockups/psn-polish/ChatScreen.tsx": () => import("../components/mockups/psn-polish/ChatScreen.tsx"),
  "./components/mockups/psn-polish/SettingsScreen.tsx": () => import("../components/mockups/psn-polish/SettingsScreen.tsx")
};
